### ISSUE TITLE
Improve language detection system to recognize C++ headers

### ISSUE THREAD

**Issue by aaronfranke** [o2sh/onefetch#26]
https://github.com/github/linguist

Linguist is a tool developed by GitHub for the specific purpose of detecting languages. It's a very mature tool that gets it right the majority of the time by using complex rules.

**Comment by o2sh** [comment]
But why ?
https://github.com/Aaronepower/tokei is written in Rust and does a great job detecting languages.

**Comment by aaronfranke** [comment]
Is that what Onefetch currently uses? It detects C++ as C in the case of Godot.

**Comment by o2sh** [comment]
it only detects the languages that are currently supported by onefetch (WIP):

    C
    Clojure
    C++
    C#
    Go
    Haskell
    Java
    Lisp
    Lua
    Python
    R
    Ruby
    Rust
    Scala
    Shell
    TypeScript
    JavaScript
    Php

Also tokei ignores all commented lines which is why the language distribution sometimes differs from GH

**Comment by aaronfranke** [comment]
Upstream issues: https://github.com/Aaronepower/tokei/issues/305 and https://github.com/Aaronepower/tokei/issues/67

We can leave this closed though if you want.

**Comment by o2sh** [comment]
Ok, with the new title it makes more sense to keep this open.

We'll wait for tokei to fix it then.

Thx @aaronfranke

**Comment by o2sh** [comment]
#https://github.com/Aaronepower/tokei/issues/67

**Comment by o2sh** [comment]
Aaronepower/tokei#67

**Comment by o2sh** [comment]
Aaronepower/tokei#67

**Comment by aaronfranke** [comment]
This issue still exists, though it is likely seen by the devs as low priority, so I'll probably have to bump this again later to please the `stale` bot.

**Comment by mapau** [comment]
Hi, I added the c header and cpp header to language.rs file to my fork
https://github.com/mapau/onefetch/tree/feature/add-c-cpp-header

https://github.com/Aaronepower/tokei already detects the c header and cpp header only the mapping in onefetch is missing.

Would be my first contribution to any GitHub Project.

**Comment by o2sh** [comment]
I'm not really fund of the idea of having separate entries for header files (CHeader and C++Header). I personally prefer the [GitHub Linguist](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) approach of extending C and C++ detection scope to include their respective header files:

```yaml
C++:
  type: programming
  tm_scope: source.c++
  ace_mode: c_cpp
  codemirror_mode: clike
  codemirror_mime_type: text/x-c++src
  color: "#f34b7d"
  aliases:
  - cpp
  extensions:
  - ".cpp"
  - ".c++"
  - ".cc"
  - ".cp"
  - ".cxx"
  - ".h"
  - ".h++"
  - ".hh"
  - ".hpp"
  - ".hxx"
  - ".inc"
  - ".inl"
  - ".ino"
  - ".ipp"
  - ".re"
  - ".tcc"
  - ".tpp"

  C:
  type: programming
  color: "#555555"
  extensions:
  - ".c"
  - ".cats"
  - ".h"
  - ".idc"
  interpreters:
  - tcc
  tm_scope: source.c
  ace_mode: c_cpp
  codemirror_mode: clike
  codemirror_mime_type: text/x-csrc
  language_id: 41
```
I'm doubt the people over at [tokei](https://github.com/XAMPPRocky/tokei/) would be ready to make that shift...So, either we follow tokei's detection rules and merge @mapau's PR, or we override the logic in Onefetch.
