### ISSUE TITLE
crazy screenshot README idea

### ISSUE THREAD

**Issue by geeseven** [o2sh/onefetch#328]
Greetings,

I had a crazy 'showerthought' idea regarding a screenshot in the `README.md` file.  What if there was automation that would create a screenshot so the `README.md` file always had an image that showed `HEAD` for this repository?  

A very rough outline how this *could* work is:

- Create a GitHub Action on commits or **merged** pull requests (not 100% sure this one is possible) to trigger a script.

- That script would do a `git pull`, build and create an image of the output of `onefetch` of the recently updated repository.

- Upload that image to imgur (or similar site)

- We can not update this repository with a new image or image link, as that would create an infinite loop.  A site like GitHub pages (or similar site) could be used to update a redirect to the new image. i.e. page.com/image ->  i.imgur.com/****.jpeg

With that being said, I recognize the effort to reward is lopsided on the outside chance someone would notice, but the reaction of those that did.  Also, my current rough outline would require managing API keys for imgur and a GitHub pages repository. 

@o2sh, seeing this is a crazy 'showerthought' idea, do not think twice about closing this issue.

**Comment by spenserblack** [comment]
>We can not update this repository with a new image or image link, as that would create an infinite loop.

The image could be kept in this repo if it is pushed to a branch besides `master` (preferably force-pushed to keep cloned repo size small). As long as the image-creation workflow only listens to changes on `master`, it shouldn't cause an infinite loop. Vaguely like this:
```yaml
steps:
  - run: mkdir dist
  - run: ./screenshot-to-dist.sh # Placeholder -- Don't know what tool would be used to get screenshots
  - run: cd dist
  - run: git init && git add *.png && git commit -m "Fetch screenshot(s)"
  - run: git push -f git@github.com/o2sh/onefetch.git master:screenshot-branch
```
This will create a temporary repo with just 1 commit, then push that commit to a branch on this repo which will not share any history with any other branches on this repo.

**Comment by geeseven** [comment]
> The image could be kept in this repo if it is pushed to a branch besides `master` 

Ahhh, that is a good idea.

**Comment by HallerPatrick** [comment]
Hey guys, I really like this idea and I am testing this myself. Maybe I am on the wrong path but I would do something like this:

```yml
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get onefetch
      run: cargo install onefetch
    - name: Execute onefetch and place in README
      run: |
          # Save output and replace in README.md
          ONEFETCH_OUTPUT=$(onefetch --no-color-palette 2>&1)
          sed -i '' "s/ONEFETCH_PLACEHOLDER/$ONEFETCH_OUTPUT/g" README.md
          
          # OR
          
          # Generate image with imagemagick
          # Required a ![Onefetch Output](./onefetch.png]
          onefetch | convert label:@- onefetch.png

   - name: Commit 
      run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add onefetch.png
          git commit -m "generated onefetch image"
          git push
```

The problem I am currently facing is that imagemagicks `convert` is not working for me well and is producing images like this:

![onefetch](https://user-images.githubusercontent.com/22773355/103155925-17891300-47a4-11eb-8949-91a7ff2c577e.png)

I am also not getting the sed command to work, because I suck at this :P
